PROJECT_NAME      = Hermes3D
# input
INPUT             = \
	${PROJECT_SOURCE_DIR}/src \
	${PROJECT_SOURCE_DIR}/common
FILE_PATTERNS     = *.cc *.h
RECURSIVE         = YES

# output
OUTPUT_DIRECTORY     = ${PROJECT_BINARY_DIR}/doc
JAVADOC_AUTOBRIEF    = YES
QUIET                = YES
WARNINGS             = NO
WARN_IF_DOC_ERROR    = NO
WARN_IF_UNDOCUMENTED = NO
WARN_NO_PARAMDOC     = NO