#
# petsc
#

SET(PETSC_DIR ${PETSC_ROOT}/${PETSC_ARCH})

FIND_PATH(PETSC_INCLUDE_DIR petsc.h ${PETSC_DIR}/include)
FIND_LIBRARY(PETSC_LIBRARY petsc ${PETSC_DIR}/lib)

IF (PETSC_INCLUDE_DIR AND PETSC_LIBRARY)
   SET(PETSC_FOUND TRUE)
ENDIF (PETSC_INCLUDE_DIR AND PETSC_LIBRARY)

IF (PETSC_FOUND)
	IF (NOT PETSC_FIND_QUIETLY)
		MESSAGE(STATUS "Found PETSc: ${PETSC_LIBRARY}")
	ENDIF (NOT PETSC_FIND_QUIETLY)
	# add path for mpiuni
	SET(PETSC_INCLUDE_DIRS ${PETSC_INCLUDE_DIR} ${PETSC_DIR}/include/mpiuni)	
	# libs has to be in this order
	FOREACH(L petscts petscsnes petscksp petscdm petscmat petscvec petsc mpiuni)
		SET(PETSC_LIBRARIES ${PETSC_LIBRARIES} ${PETSC_DIR}/lib/lib${L}.a)
	ENDFOREACH(L)
	SET(PETSC_LIBRARIES ${PETSC_LIBRARIES} dl)
ELSE (PETSC_FOUND)
	IF (PETSC_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find PETSc")
	ENDIF (PETSC_FIND_REQUIRED)
ENDIF (PETSC_FOUND)
