#
# ZLIB
#

FIND_FILE(ZLIB_LIBRARY libz.a ${ZLIB_ROOT}/lib /usr/lib64/ /usr/lib/ /usr/X11R6/lib64/ /usr/X11R6/lib/ /lib) 

IF (ZLIB_LIBRARY)
	SET(ZLIB_FOUND TRUE)
ENDIF (ZLIB_LIBRARY)


IF (ZLIB_FOUND)
	IF (NOT ZLIB_FIND_QUIETLY)
		MESSAGE(STATUS "Found ZLIB: ${ZLIB_LIBRARY}")
	ENDIF (NOT ZLIB_FIND_QUIETLY)
ELSE (ZLIB_FOUND)
	IF (ZLIB_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find ZLIB")
	ENDIF (ZLIB_FIND_REQUIRED)
ENDIF (ZLIB_FOUND)

