#
# SLEPc
#

FIND_PATH(SLEPC_INCLUDE_DIR slepc.h ${SLEPC_ROOT}/include)

SET(SLEPC_LIB_DIR ${SLEPC_ROOT}/${SLEPC_ARCH}/lib)
FIND_LIBRARY(SLEPC_LIBRARY slepc ${SLEPC_LIB_DIR}) 

IF (SLEPC_INCLUDE_DIR AND SLEPC_LIBRARY)
   SET(SLEPC_FOUND TRUE)
ENDIF (SLEPC_INCLUDE_DIR AND SLEPC_LIBRARY)

IF (SLEPC_FOUND)
	IF (NOT SLEPC_FIND_QUIETLY)
		MESSAGE(STATUS "Found SLEPc: ${SLEPC_LIBRARY}")
	ENDIF (NOT SLEPC_FIND_QUIETLY)
	SET(SLEPC_INCLUDE_DIRS ${SLEPC_INCLUDE_DIR})
ELSE (SLEPC_FOUND)
	IF (SLEPC_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find SLEPc")
	ENDIF (SLEPC_FIND_REQUIRED)
ENDIF (SLEPC_FOUND)

