#
# MPI
#

FIND_PATH(MPI_INCLUDE_DIR mpio.h ${MPI_ROOT}/include)
FIND_LIBRARY(MPI_LIBRARY mpich ${MPI_ROOT}/lib) 

IF (MPI_INCLUDE_DIR AND MPI_LIBRARY)
	SET(MPI_FOUND TRUE)
ENDIF (MPI_INCLUDE_DIR AND MPI_LIBRARY)


IF (MPI_FOUND)
	IF (NOT MPI_FIND_QUIETLY)
		MESSAGE(STATUS "Found MPI: ${MPI_LIBRARY}")
	ENDIF (NOT MPI_FIND_QUIETLY)
ELSE (MPI_FOUND)
	IF (MPI_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find MPI")
	ENDIF (MPI_FIND_REQUIRED)
ENDIF (MPI_FOUND)

