#
# Fortran
#

FIND_LIBRARY(FORTRAN_LIBRARY ${USE_FORTRAN} ${FORTRAN_ROOT} /usr/lib64 /usr/lib /usr/local/lib64 /usr/local/lib) 

IF (FORTRAN_LIBRARY)
	SET(FORTRAN_FOUND TRUE)
ENDIF (FORTRAN_LIBRARY)

IF (FORTRAN_FOUND)
	IF (NOT FORTRAN_FIND_QUIETLY)
		MESSAGE(STATUS "Found FORTRAN: ${FORTRAN_LIBRARY}")
	ENDIF (NOT FORTRAN_FIND_QUIETLY)
ELSE (FORTRAN_FOUND)
	IF (FORTRAN_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find FORTRAN")
	ENDIF (FORTRAN_FIND_REQUIRED)
ENDIF (FORTRAN_FOUND)

