#
# ACML (AMD Core Math Library)
#

FIND_PATH(ACML_INCLUDE_DIR acml.h ${ACML_ROOT}/include /usr/include /usr/local/include)
FIND_LIBRARY(ACML_LIBRARY acml ${ACML_ROOT}/lib /usr/lib64 /usr/lib /usr/local/lib64 /usr/local/lib) 

IF (ACML_INCLUDE_DIR AND ACML_LIBRARY)
	SET(ACML_FOUND TRUE)
ENDIF (ACML_INCLUDE_DIR AND ACML_LIBRARY)


IF (ACML_FOUND)
	IF (NOT ACML_FIND_QUIETLY)
		MESSAGE(STATUS "Found ACML: ${ACML_LIBRARY}")
	ENDIF (NOT ACML_FIND_QUIETLY)
ELSE (ACML_FOUND)
	IF (ACML_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find ACML")
	ENDIF (ACML_FIND_REQUIRED)
ENDIF (ACML_FOUND)

