#
# petsc
#

FIND_PATH(PETSC_INCLUDE_DIR petsc.h ${PETSC_ROOT}/include)

SET(PETSC_LIB_DIR ${PETSC_ROOT}/lib/${PETSC_ARCH})
FIND_LIBRARY(PETSC_LIBRARY petsc ${PETSC_LIB_DIR}) 

IF (PETSC_INCLUDE_DIR AND PETSC_LIBRARY)
   SET(PETSC_FOUND TRUE)
ENDIF (PETSC_INCLUDE_DIR AND PETSC_LIBRARY)


IF (PETSC_FOUND)
	IF (NOT PETSC_FIND_QUIETLY)
		MESSAGE(STATUS "Found Petsc: ${PETSC_LIBRARY}")
	ENDIF (NOT PETSC_FIND_QUIETLY)
	SET(PETSC_INCLUDE_DIRS
		${PETSC_INCLUDE_DIR}
		${PETSC_ROOT}/bmake/${PETSC_ARCH}
		${PETSC_ROOT}/include/mpiuni
	)
	
	# libs has to be in this order
	FOREACH(L petscts petscsnes petscksp petscdm petscmat petscvec petsc mpiuni)
		SET(PETSC_LIBRARIES ${PETSC_LIBRARIES} ${PETSC_LIB_DIR}/lib${L}.a)
	ENDFOREACH(L)
ELSE (PETSC_FOUND)
	IF (PETSC_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find PETSC")
	ENDIF (PETSC_FIND_REQUIRED)
ENDIF (PETSC_FOUND)

