#
# BLAS (Basic Linear Algebra Subroutins)
#

FIND_LIBRARY(BLAS_LIBRARY blas ${BLAS_ROOT} /usr/lib64 /usr/lib /usr/local/lib64 /usr/local/lib) 

IF (BLAS_LIBRARY)
	SET(BLAS_FOUND TRUE)
ENDIF (BLAS_LIBRARY)


IF (BLAS_FOUND)
	IF (NOT BLAS_FIND_QUIETLY)
		MESSAGE(STATUS "Found BLAS: ${BLAS_LIBRARY}")
	ENDIF (NOT BLAS_FIND_QUIETLY)
ELSE (BLAS_FOUND)
	IF (BLAS_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find BLAS")
	ENDIF (BLAS_FIND_REQUIRED)
ENDIF (BLAS_FOUND)

