#
# Fortran
#

IF(CMAKE_COMPILER_IS_GNUCC)
    EXECUTE_PROCESS(COMMAND /usr/bin/gcc -print-search-dirs OUTPUT_VARIABLE GCC_SEARCH_DIRS)
    STRING(REGEX REPLACE "install: (.+)programs:.*" "\\1" GCC_INSTALL_PATH "${GCC_SEARCH_DIRS}")
    STRING(STRIP "${GCC_INSTALL_PATH}" GCC_INSTALL_PATH)
ELSE(CMAKE_COMPILER_IS_GNUCC)
    MESSAGE(STATUS "Warning: not using a gnu C compatible compiler - might have problems with linking fortran")
ENDIF(CMAKE_COMPILER_IS_GNUCC)

FIND_LIBRARY(FORTRAN_LIBRARY ${USE_FORTRAN} ${FORTRAN_ROOT} ${GCC_INSTALL_PATH})

IF(FORTRAN_LIBRARY)
	SET(FORTRAN_FOUND TRUE)
ENDIF(FORTRAN_LIBRARY)

IF(FORTRAN_FOUND)
	IF(NOT FORTRAN_FIND_QUIETLY)
		MESSAGE(STATUS "Found FORTRAN: ${FORTRAN_LIBRARY}")
	ENDIF(NOT FORTRAN_FIND_QUIETLY)
ELSE(FORTRAN_FOUND)
	IF(FORTRAN_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find FORTRAN")
	ENDIF(FORTRAN_FIND_REQUIRED)
ENDIF(FORTRAN_FOUND)

