#
# LAPACK (Basic Linear Algebra Subroutins)
#

FIND_LIBRARY(LAPACK_LIBRARY lapack ${LAPACK_ROOT} /usr/lib64 /usr/lib /usr/local/lib64 /usr/local/lib) 

IF (LAPACK_LIBRARY)
	SET(LAPACK_FOUND TRUE)
ENDIF (LAPACK_LIBRARY)


IF (LAPACK_FOUND)
	IF (NOT LAPACK_FIND_QUIETLY)
		MESSAGE(STATUS "Found LAPACK: ${LAPACK_LIBRARY}")
	ENDIF (NOT LAPACK_FIND_QUIETLY)
ELSE (LAPACK_FOUND)
	IF (LAPACK_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find LAPACK")
	ENDIF (LAPACK_FIND_REQUIRED)
ENDIF (LAPACK_FOUND)

